package org.motechproject.ws;

public enum InterestReason {
	CURRENTLY_PREGNANT, RECENTLY_DELIVERED, FAMILY_FRIEND_PREGNANT, FAMILY_FRIEND_DELIVERED, PLANNING_PREGNANCY_INFO, KNOW_MORE_PREGNANCY_CHILDBIRTH, WORK_WITH_WOMEN_NEWBORNS,
}
